name: Auto-Changelog for Dependabot Pull Requests

on:
  pull_request:
    branches:
      - master
      - 'release/**'
    types: [opened, synchronize]

jobs:
  generate-changelog-entry:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/dependabot_auto_changelog_template.yml@v2.1.1
