name: Dependency Scan Template
on:
  workflow_call:
    inputs:
      jdk-version:
        required: false
        description: 'Version of jdk that is used.'
        type: number
        default: 17
      checkout-lfs:
          required: false
          description: 'Checkout files from Git LFS'
          type: boolean
          default: false
      snyk-organization:
        required: false
        description: 'Snyk organization ID'
        type: string
      snyk-reference:
        required: true
        description: 'Target reference for snyk project'
        type: string
    secrets:
      SNYK_TOKEN:
        required: true
        description: 'Token to authenticate Snyk CLI'

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  Monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.checkout-lfs }}
      - name: Setup snyk
        uses: snyk/actions/setup@master
      - name: Setup JDK ${{ inputs.jdk-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.jdk-version }}
          distribution: temurin
          cache: maven
      - name: Create dependency snapshot to monitor for vulnerabilities
        run: > 
          snyk monitor 
          --maven-aggregate-project 
          --target-reference=${{ inputs.snyk-reference }} --org=${{ inputs.snyk-organization }}
