name: Semgrep Scan

on:
  pull_request:
    branches:
      - master
  workflow_dispatch: { }

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.checkout-lfs }}
          fetch-depth: 0

      - name: Run semgrep scan on changed files
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          TARGET_BRANCH="origin/${{ github.base_ref }}"

          semgrep scan \
              --error \
              --json --json-output semgrep-report.json \
              --metrics=off \
              --config="p/default" \
              $(git diff --name-only $(git merge-base $TARGET_BRANCH HEAD))

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report.json
          path: semgrep-report.json
